# The following sources were used to create this machine file:
# https://github.com/nxp-imx-support/meta-imx-frdm/blob/lf-6.6.36-2.1.0/meta-imx-bsp/conf/machine/imx8mp-lpddr4-frdm.conf
# https://github.com/nxp-imx-support/meta-imx-frdm/blob/lf-6.6.36-2.1.0/meta-imx-bsp/conf/machine/imx8mpfrdm.conf
# The meta-imx-frdm layer is not compatible with Yocto Wrynose, so this machine file is a derived copy of
# the above files with modifications to make it compatible with Yocto Wrynose.
# Credit to NXP for the original files and their work on supporting the FRDM board.

MACHINEOVERRIDES =. "imx8mp-lpddr4-frdm:"

require conf/machine/include/imx8mp-evk.inc

# The device tree name is implicit for LPDDR4, so can't use MACHINE here
KERNEL_DEVICETREE_BASENAME = "imx8mp-frdm"

# NXP kernel has additional DTB files for various board configuration and
# derivates. Include them here for NXP BSP only
KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    freescale/${KERNEL_DEVICETREE_BASENAME}-boe-wuxga-lvds0-panel.dtb \
    freescale/${KERNEL_DEVICETREE_BASENAME}-boe-wuxga-lvds1-panel.dtb \
    freescale/${KERNEL_DEVICETREE_BASENAME}-os08a20.dtb \
    freescale/${KERNEL_DEVICETREE_BASENAME}-rpmsg.dtb \
"
# freescale/${KERNEL_DEVICETREE_BASENAME}-8mic.dtb 
# freescale/${KERNEL_DEVICETREE_BASENAME}-dual-ap1302.dtb 
# freescale/${KERNEL_DEVICETREE_BASENAME}-dual-os08a20.dtb 
# freescale/${KERNEL_DEVICETREE_BASENAME}-waveshare.dtb
# freescale/${KERNEL_DEVICETREE_BASENAME}-iw612-otbr.dtb  

UBOOT_CONFIG_BASENAME = "imx8mp_frdm"
UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"

# Set DDR FIRMWARE
DDR_FIRMWARE_VERSION = "202006"
DDR_FIRMWARE_NAME = " \
    lpddr4_pmu_train_1d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_1d_imem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_imem_${DDR_FIRMWARE_VERSION}.bin \
"

IMXBOOT_TARGETS_BASENAME = "flash_evk"

# Mainline BSP doesn't support LPDDR4 so it must be set to nxp.
# Also this machine isn't supported by u-boot-fslc but imx8mn-evk.inc already
# set the bootloader to u-boot-imx instead when NXP BSP is used.
IMX_DEFAULT_BSP = "nxp"

