#@TYPE: Machine
#@NAME: Radxa Rock 5T
#@DESCRIPTION: ROCK5 is the 5th generation of SBC designed by Radxa.
#https://docs.radxa.com/en/rock5/rock5t

require conf/machine/include/rk3588.inc

# arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
KERNEL_DEVICETREE = "rockchip/rk3588-rock-5t.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
# PREFERRED_PROVIDER_virtual/bootloader = "u-boot-rockchip"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
UBOOT_MACHINE = "rock5t-rk3588_defconfig"
# UBOOT_MACHINE = "rk3588_defconfig"
